name: poppycorn
description: A SUPER IPTV MEDIA PLAYER.
author: POPPYCORN TV <contact@poppycorn.tv>
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_animate: ^4.5.0
  #flutter_native_splash: ^2.4.3
  #device_uuid: ^0.0.4
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  heroicons_flutter: ^0.4.0
  wakelock_plus: ^1.2.8
  connectivity_plus: ^5.0.1
  url_launcher: ^6.3.0
  dio: ^5.7.0
  email_otp: ^2.1.2
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  youtube_player_iframe: ^5.2.1
  uuid: ^4.5.1
  device_info_plus: ^11.1.1
  connectivity_plus_tizen:
  package_info_plus_tizen:
  path_provider_tizen:
  url_launcher_tizen:
  sqflite_tizen:
  device_info_plus_tizen:
  video_player_videohole: ^0.5.3
  #pod_player: ^0.2.2
  #perfect_volume_control: ^1.0.5
  #firebase_core: ^2.29.0
  #firebase_core_web: ^2.15.0
  #firebase_messaging: ^14.8.1
  #firebase_analytics: ^10.10.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#flutter_native_splash:
  #  android: true
  # color: "#352A6E"
  #  image: assets/images/splash_logo.png
  #  fullscreen: true
    #  android_12:
#    image: assets/images/splash_logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/animated/