// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
/*import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9IX-oazgkAq573EorGhbKJKknj3FAes',
    appId: '1:705036334909:web:b54eef7297574f3ffb7754',
    messagingSenderId: '705036334909',
    projectId: 'poppycorn-60d8c',
    authDomain: 'poppycorn-60d8c.firebaseapp.com',
    storageBucket: 'poppycorn-60d8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXPgYtNP7QhJXD2gAmy6MjVS466v6LX8',
    appId: '1:705036334909:android:99ce6d91fcc24979fb7754',
    messagingSenderId: '705036334909',
    projectId: 'poppycorn-60d8c',
    storageBucket: 'poppycorn-60d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhjgsgwC4Ur8s5G3fQlXh3z5zTOr38aPw',
    appId: '1:705036334909:ios:40250e1ea1177041fb7754',
    messagingSenderId: '705036334909',
    projectId: 'poppycorn-60d8c',
    storageBucket: 'poppycorn-60d8c.appspot.com',
    iosBundleId: 'com.poppycorn.rax.poppycorn',
  );
}
*/